---
product_name: IntelliJ Platform SDK
product_version:
product_type: DevGuide

baseurl: /intellij/sdk/docs/

# This is tag 171.3780.107 (2017.1)
upsource:
  server: upsource.jetbrains.com
  repo: idea-ce
  commit: d00d8b4ae3ed33097972b8a4286b336bf4ffcfab

github_repo: JetBrains/intellij-sdk-docs
