product_name: IntelliJ Platform SDK
product_version:
search_scope: null
use_side_blocks: true
show_disqus: false

webhelp_app_baseurl: /
markdown: kramdown
markdown_ext: foo
kramdown:
  input: GFM2
  hard_wrap: false
  auto_ids: false
highlighter: pygments

exclude:
  - '*.scss'
  - README*
  - Rakefile
  - webhelp-template
  - code_samples

defaults:
  - values:
      layout: 'webhelp'

edit_on_github_url: https://github.com/JetBrains/intellij-sdk-docs/edit/master/%path%