---
product_name: IntelliJ Platform SDK
product_version:
product_type: DevGuide

url: https://www.jetbrains.org
baseurl: /intellij/sdk/docs/

description: Documentation for working with and extending the IntelliJ Platform SDK

# This is tag 193.5662.53 (2019.3.1)
upsource:
  server: upsource.jetbrains.com
  repo: idea-ce
  commit: 7cf49a16e4e15a18fa2f742635053647ae94abfb

github_repo: JetBrains/intellij-sdk-docs
youtrack_project: IJSDK

exclude:
  - code_samples